name: Publish Project

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Configure git user and email
        run: |
          git config --global user.name "jinzelin"
          git config --global user.email "jinzelin@tencent.com"

      - name: Install Dependencies
        run: |
          npm install yarn -g
          yarn

      - name: Publish to NPM
        run: |
          yarn build
          npx lerna publish -y --legacy-auth $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Doc
        run: yarn doc:publish
